from typing import Dict, List, Optional
from .tensor import Tensor, DType, Device
from .autocast import autocast, GradScaler
from . import nn
from . import optim
from . import data
from . import callbacks
from . import distributed
from . import onnx
from . import zoo
from . import hf

# Factory functions
def zeros(shape: List[int], dtype: Optional[DType] = None, device: Optional[Device] = None, requires_grad: bool = False) -> Tensor: ...
def ones(shape: List[int], dtype: Optional[DType] = None, device: Optional[Device] = None, requires_grad: bool = False) -> Tensor: ...
def scalar(value: float, dtype: Optional[DType] = None, device: Optional[Device] = None, requires_grad: bool = False) -> Tensor: ...
def randn(shape: List[int], mean: float = 0.0, std: float = 1.0, dtype: Optional[DType] = None, device: Optional[Device] = None, requires_grad: bool = False) -> Tensor: ...
def rand_uniform(shape: List[int], low: float, high: float, dtype: Optional[DType] = None, device: Optional[Device] = None, requires_grad: bool = False) -> Tensor: ...
def rand_dropout_mask(shape: List[int], p: float, dtype: Optional[DType] = None, device: Optional[Device] = None) -> Tensor: ...
def from_list(data: List[float], shape: Optional[List[int]] = None, requires_grad: bool = False, device: Optional[Device] = None) -> Tensor: ...

def save_tensors(path: str, tensors_dict: Dict[str, Tensor]) -> None: ...
def load_tensors(path: str) -> Dict[str, Tensor]: ...
def einsum(equation: str, *operands: Tensor) -> Tensor: ...
def set_grad_enabled(enabled: bool) -> None: ...
def is_grad_enabled() -> bool: ...

class no_grad:
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type: any, exc_val: any, exc_tb: any) -> None: ...
    def __call__(self, func: any) -> any: ...

__version__: str
__all__ = [
    "Tensor", "DType", "Device", "save_tensors", "load_tensors", "einsum", 
    "autocast", "GradScaler", "nn", "optim", "data", "callbacks", "onnx", "zoo", "hf",
    "distributed", "zeros", "ones", "scalar", "randn", "rand_uniform",
    "rand_dropout_mask", "from_list", "no_grad", "set_grad_enabled", "is_grad_enabled"
]
