from .nn.module import Module

class DistributedDataParallel(Module):
    def __init__(self, module: Module, rank: int = 0, world_size: int = 1) -> None: ...
    def forward(self, *args: any, **kwargs: any) -> any: ...
    def all_reduce_gradients(self) -> None: ...
